const applicationController = require('../controllers/application.controller')
module.exports = require('express').Router()
    .get('/list', applicationController.getAll)
    .get('/detail', applicationController.getOne)
    .get('/get-by-jobid', applicationController.getAllByJobId)
    .post('/create', applicationController.create)